production:
  contact_types:
    - person
    - company
  role_statuses:
    - active
    - inactive
    - discontinued
  default_visibility: private
  enable_groups: true
  enable_issue_links: true
  enable_custom_fields: true
  enable_attachments: true
  default_workload_hours: 8

development:
  contact_types:
    - person
    - company
  role_statuses:
    - active
    - inactive
    - discontinued
  default_visibility: private
  enable_groups: true
  enable_issue_links: true
  enable_custom_fields: true
  enable_attachments: true
  default_workload_hours: 8

test:
  contact_types:
    - person
    - company
  role_statuses:
    - active
    - inactive
    - discontinued
  default_visibility: private
  enable_groups: true
  enable_issue_links: true
  enable_custom_fields: true
  enable_attachments: true
  default_workload_hours: 8